name: Telegram Bot Automation

on:
  schedule:
    # 21:30 UTC معادل 01:00 به وقت تهران است.
    - cron: "30 21 * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Telegram Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          SOURCE_CHANNEL_1: ${{ secrets.SOURCE_CHANNEL_1 }}
          SOURCE_CHANNEL_2: ${{ secrets.SOURCE_CHANNEL_2 }}
          TARGET_CHANNEL: ${{ secrets.TARGET_CHANNEL }}
        run: |
          python bot.py
